// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7YFiFEdnm7VR7wj6_Rc164na_e7jylK0',
    appId: '1:426323123768:web:52524fea168b49bb1c90cd',
    messagingSenderId: '426323123768',
    projectId: 'little-momo-0187',
    authDomain: 'little-momo-0187.firebaseapp.com',
    storageBucket: 'little-momo-0187.firebasestorage.app',
    measurementId: 'G-VWNEV1CK5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvrf44J3LvUL8VIkUq4mM_XwUGa3SSbqw',
    appId: '1:426323123768:android:f001a8ab4b6af02c1c90cd',
    messagingSenderId: '426323123768',
    projectId: 'little-momo-0187',
    storageBucket: 'little-momo-0187.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEHaXPW-YAL_i9S2l9HySNS8uQsJhirx0',
    appId: '1:426323123768:ios:37d1a14a717e64d11c90cd',
    messagingSenderId: '426323123768',
    projectId: 'little-momo-0187',
    storageBucket: 'little-momo-0187.firebasestorage.app',
    iosBundleId: 'com.example.littleMomo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEHaXPW-YAL_i9S2l9HySNS8uQsJhirx0',
    appId: '1:426323123768:ios:37d1a14a717e64d11c90cd',
    messagingSenderId: '426323123768',
    projectId: 'little-momo-0187',
    storageBucket: 'little-momo-0187.firebasestorage.app',
    iosBundleId: 'com.example.littleMomo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7YFiFEdnm7VR7wj6_Rc164na_e7jylK0',
    appId: '1:426323123768:web:b346140c4767358f1c90cd',
    messagingSenderId: '426323123768',
    projectId: 'little-momo-0187',
    authDomain: 'little-momo-0187.firebaseapp.com',
    storageBucket: 'little-momo-0187.firebasestorage.app',
    measurementId: 'G-2RV81GBHZ6',
  );
}
